### ISSUE TITLE
Why are the deployment expenses such high?

### ISSUE THREAD

**Issue by dannyyy** [solana-labs/example-helloworld#311]
I followed this tutorial and was able to successfully deploy the program and query the counter with the client app. I did the whole thing on devnet. What me shocked a bit was the high amount of SOL I had to pay for the deployment. At the beginning I airdroped my account with 10 SOL. After deployment I had only ~9.15 SOL remaining. Converted to USD, I had to pay roughly 150 USD to deploy such a simple program?

Before the airdrop I received the following message:
`Account CYW9nog4sKTxAHLNcprZHEykUGgHFgko4PdhiaYTYimZ has insufficient funds for spend (0.4265436 SOL) + fee (0.001355 SOL)`

**Comment by jstarry** [comment]
Deployed programs are still pretty large and so they need to pay higher rent fees. With Solana's account model, it's pretty common for projects to reuse certain programs which saves on cost. For example, you don't need to deploy a new program for a new token or NFT collection. In the future, we hope that validators can increase storage capacity and the rent costs can then go down. But for now, we need higher rent so that people don't abuse the storage.
